name: \ud83d\ude97 E2E Tests

on:
  push:
    branches: [main, master, dev] # Adjust branches as needed
  pull_request:
    branches: [main, master, dev]
  workflow_dispatch: # Allows manual triggering

jobs:
  e2e:
    name: \ud83c\udfc3 Run Playwright E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15 # Set a timeout for the job

    env:
      # Supabase credentials for the application to connect to the database
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }} # If needed by app during E2E tests

      # Admin credentials for Playwright tests to log in
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

      # Base URL for Playwright tests (can be overridden if needed)
      PLAYWRIGHT_BASE_URL: "http://localhost:3005" 

      # Disable color for cleaner logs in CI
      NO_COLOR: "1"
      FORCE_COLOR: "0"

    steps:
      - name: \ud83d\udce5 Checkout code
        uses: actions/checkout@v4

      - name: \ud83d\udd27 Set up Node.js and Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # Or specify a particular Bun version

      - name: \ud83d\udce6 Install dependencies
        run: bun install --frozen-lockfile # Use frozen lockfile for CI

      - name: \ud83e\udddf Install Playwright Browsers
        run: bunx playwright install --with-deps # Installs browsers and their OS dependencies

      - name: \ud83d\udea7 Run Playwright E2E tests
        # This command assumes your Playwright tests are configured to run against PLAYWRIGHT_BASE_URL
        # and that your development server is started by Playwright's webServer config
        run: bunx playwright test
        env:
          CI: "true" # Indicate to Playwright that it's running in CI

      - name: \ud83d\udcca Upload Playwright report
        if: always() # Upload report even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/ # Default Playwright HTML report output directory
          retention-days: 7 # Keep reports for 7 days 