name: Email Service Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'lib/services/email-service-resend.ts'
      - 'app/api/email/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'lib/services/email-service-resend.ts'
      - 'app/api/email/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run email service tests
      run: npm test -- __tests__/email-service.test.ts
      env:
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
