name: Email Service Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'lib/services/email-service-resend.ts'
      - 'app/api/email/**'
      - '__tests__/email-service.test.ts'
      - '.github/workflows/email-test.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'lib/services/email-service-resend.ts'
      - 'app/api/email/**'
      - '__tests__/email-service.test.ts'
      - '.github/workflows/email-test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 🔧 Set up Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install
    
    - name: Verify email service files exist
      run: |
        if [ -f "lib/services/email-service-resend.ts" ] && [ -f "app/api/email/contact/route.ts" ] && [ -f "app/api/email/booking/route.ts" ]; then
          echo "Email service files verified successfully"
        else
          echo "Email service files missing"
          exit 1
        fi
    
    - name: Create reports directory
      run: mkdir -p reports

    - name: Run email service tests
      run: bun vitest run --reporter=default --reporter=junit --outputFile.junit=reports/junit.xml --preload __tests__/setup.ts -- __tests__/email-service.test.ts
      env:
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

    - name: Publish Test Report
      uses: dorny/test-reporter@v2
      if: success() || failure()
      with:
        name: Email Service Tests Report
        path: reports/junit.xml
        reporter: jest-junit
        fail-on-error: 'true'
