name: Email Service Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'lib/services/email-service-resend.ts'
      - 'app/api/email/**'
      - '__tests__/email-service.test.ts'
      - '.github/workflows/email-test.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'lib/services/email-service-resend.ts'
      - 'app/api/email/**'
      - '__tests__/email-service.test.ts'
      - '.github/workflows/email-test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install
    
    - name: Verify email service files exist
      run: |
        missing_files=()
        for file in "lib/services/email-service-resend.ts" "app/api/email/contact/route.ts" "app/api/email/booking/route.ts"; do
          if [ ! -f "$file" ]; then
            echo "Missing file: $file"
            missing_files+=("$file")
          else
            echo "Found file: $file"
          fi
        done
        
        if [ ${#missing_files[@]} -ne 0 ]; then
          echo "⚠️ The following files are missing:"
          printf '%s\n' "${missing_files[@]}"
          exit 1
        else
          echo "✅ All required files verified successfully"
        fi
    
    - name: Create setup.ts file
      run: |
        # Create a proper setup.ts file using the actual content
        echo '// setup.ts' > setup.ts
        echo "import { beforeAll, afterAll } from 'vitest';" >> setup.ts
        echo "" >> setup.ts
        echo "// Setup logic before all tests" >> setup.ts
        echo "beforeAll(() => {" >> setup.ts
        echo "    console.log('Setting up test environment...');" >> setup.ts
        echo "    process.env.RESEND_API_KEY = 'test-api-key'; // Example environment variable" >> setup.ts
        echo "});" >> setup.ts
        echo "" >> setup.ts
        echo "// Cleanup logic after all tests" >> setup.ts
        echo "afterAll(() => {" >> setup.ts
        echo "    console.log('Cleaning up test environment...');" >> setup.ts
        echo "});" >> setup.ts
        
        # Verify the setup.ts file was created
        echo "Content of setup.ts:"
        cat setup.ts

    - name: Run email service tests
      run: |
        echo "Running tests with Bun version: $(bun --version)"
        # Run the test without specifying preload as it's already in bunfig.toml
        bun test __tests__/email-service.test.ts
      env:
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
